export const listProyek = [
  {
    id: 1,
    gambar: "/assets/proyek/Surplusin.webp",
    nama: "Surplusin",
    desk: "Surplusin adalah sebuah platform yang menyediakan layanan untuk mengelola sisa stok makanan dari restoran, toko, dan produsen makanan. Platform ini bertujuan untuk mengurangi pemborosan makanan dengan menghubungkan penyedia makanan dengan konsumen yang membutuhkan. Pengguna dapat mencari sisa stok makanan berdasarkan lokasi, sementara penyedia makanan dapat mengurangi limbah dan mengoptimalkan penggunaan sisa makanan.",
    tools: ["ExpressJS", "PostgreSQL", "TypeScript", "Postman", "Vercel"],
    link: "https://surplusin.vercel.app/",
    linkGithub: "https://github.com/samuel-geraldo/Surplusin-BE",
    dad: "200",
  },
  {
    id: 2,
    gambar: "/assets/proyek/WebKopiNusantara.webp",
    nama: "Kopi Nusantara",
    desk: "Kopi nusantara adalah sebuah website yang digunakan untuk mengoptimalisasi penjualan pada cafe kopi nusantara.",
    tools: ["PHP", "JavaScript", "MySQL"],
    linkGithub: "https://github.com/Gojikkk/Project-P-Web",
    dad: "300",
  },
  {
    id: 3,
    gambar: "/assets/proyek/AndroProject.webp",
    nama: "Pemesanan Terminal Bus",
    desk: "Bus Ticket Booking API adalah mini project backend yang dibangun menggunakan Node.js untuk mengelola pemesanan tiket bus. Sistem menyediakan endpoint REST API untuk mmengelola data penumpang,bus, dan terminal yang diuji menggunakan Postman.",
    tools: ["Node.js", "JavaScript", "Postman"],
    linkGithub:"https://github.com/Gojikkk/Andro-Project",
    dad: "400",
  },
];
